apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.bonus.name }}
spec:
    selector:
        app: {{ .Values.bonus.name }}
    ports:
      - name: {{ .Values.bonus.name }}-listener
        protocol: TCP
        port: 8050
        targetPort: {{ .Values.bonus.name }}