apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.flight.name }}
spec:
    selector:
        app: {{ .Values.flight.name }}
    ports:
      - name: {{ .Values.flight.name }}-listener
        protocol: TCP
        port: 8060
        targetPort: {{ .Values.flight.name }}
