apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.ticket.name }}
spec:
    selector:
        app: {{ .Values.ticket.name }}
    ports:
      - name: {{ .Values.ticket.name }}-listener
        protocol: TCP
        port: 8070
        targetPort: {{ .Values.ticket.name }}